# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13718361ede87d9db6236a25bae70903aae7c68fdb1358a97fe93e16223cdaf0808c5f56b52a9e6ddd9a84963087c7f5eedd0f020c9aebd33d4da07d9a6edf43

test:
  secret_key_base: 87f7ef03f9513c6575e0907b429fbf3ff7deecc1c3a1759dd80141824e13827a7e0d356822f7533966a443d572cc55d02c750d127285e881ed32c47464ab27ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
